

############################################        ОФИС        #################################################################################

# Интегральный сенсор преобразования потребленных "W" в "kWh" (оставляем как есть)
- platform: integration
  source: sensor.in_220_office_power
  name: in_220_office_energy_integral
  round: 2
  method: left

# Интегральный сенсор преобразования потребленных "W" в "kWh" (ферма)
- platform: integration
  source: sensor.energy_farm_power
  name: energy_farm_power_integral
  round: 2
  method: left


##########################################################################################################################
