
# Сенсор текущих месячных затрат электрики день
- platform: template
  sensors:
    energy_count_difference_day:
      friendly_name: "Energy Count Difference Day"
      value_template: "{{ ((states('sensor.energy_counter_day') | float) - (states('input_number.energy_count_day_last_month') | float)) | round(1) }}"
      unit_of_measurement: "kWh"

# Сенсор текущих месячных затрат электрики ночь
- platform: template
  sensors:
    energy_count_difference_night:
      friendly_name: "Energy Count Difference Night"
      value_template: "{{ ((states('sensor.energy_counter_night') | float) - (states('input_number.energy_count_night_last_month') | float)) | round(1) }}"
      unit_of_measurement: "kWh"

# Сенсор текущих месячных затрат электрики в деньгах день
- platform: template
  sensors:
    energy_count_difference_price_day:
      friendly_name: "Energy Count Difference Price Day"
      value_template: "{{ ((states('sensor.energy_count_difference_day') | float) * (states('input_number.price_energy_day') | float)) | round(1) }}"
      unit_of_measurement: "₴"
      icon_template: "mdi:currency-uah"

# Сенсор текущих месячных затрат электрики в деньгах ночь
- platform: template
  sensors:
    energy_count_difference_price_night:
      friendly_name: "Energy Count Difference Price Night"
      value_template: "{{ ((states('sensor.energy_count_difference_night') | float) * (states('input_number.price_energy_night') | float)) | round(1) }}"
      unit_of_measurement: "₴"
      icon_template: "mdi:currency-uah"

# Сенсор газа
- platform: template
  sensors:
    gas_count_difference:
      friendly_name: "Gas Count Difference"
      value_template: "{{ (states('input_number.gas_counter') | float) | round(1) }}"
      unit_of_measurement: "m3"
      icon_template: "mdi:gas-burner"

# Сенсор текущих месячных затрат газ
- platform: template
  sensors:
    gas_count_difference_month:
      friendly_name: "Gas Count Difference Month"
      value_template: "{{ ((states('sensor.gas_meter') | float) - (states('input_number.gas_count_last_month') | float)) | round(1) }}"
      unit_of_measurement: "m3"
      icon_template: "mdi:gas-burner"

# Сенсор текущих месячных затрат газ в деньгах
- platform: template
  sensors:
    gas_count_difference_price_month:
      friendly_name: "Gas Count Difference Price Month"
      value_template: "{{ ((states('sensor.gas_count_difference_month') | float) * (states('input_number.price_gas') | float)) | round(1) }}"
      unit_of_measurement: "₴"
      icon_template: "mdi:currency-uah"