homeassistant:
  packages: !include_dir_merge_named includes/packages/
  time_zone: "Europe/Kiev"
  
  unit_system: metric
# Loads default set of integrations. Do not remove.
default_config:

# Включаем python script
python_script:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes/

#Вынос в файл
script: !include scripts.yaml
scene: !include scenes.yaml

#Вынос в папку
automation: !include_dir_merge_list automations
input_text: !include_dir_merge_named variables/input_text
input_boolean: !include_dir_merge_named variables/input_boolean
input_number: !include_dir_merge_named variables/input_number

climate: !include includes/mi_custom_devices/climate.yaml
sensor: !include includes/mi_custom_devices/sensors.yaml

recorder: !include includes/recorder.yaml
history:
logbook:

#Вынос system в боковую панель
panel_custom:
  - name: server_state
    sidebar_title: 'System'
    sidebar_icon: mdi:server
    js_url: /api/hassio/app/entrypoint.js
    url_path: 'hassio/system'
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator     

# Включаем службу SUN         
sun:
  
# Включаем индивидуальный интерфейс
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module

# Включаем http
http:
    use_x_forwarded_for: true
    trusted_proxies:
      - 0.0.0.0/0

# Время заката и рассвета выводим в сенсоры



