views:

  - title: Home
    icon: mdi:view-dashboard
    cards:
      !include ui-lovelace/home.yaml

  - title: Heating
    icon: mdi:view-dashboard
    cards:
      !include ui-lovelace/heating.yaml



