views:

  - title: Home
    icon: mdi:view-dashboard
    cards:
      !include /config/ui-lovelace/home.yaml

  - title: Heating
    icon: mdi:view-dashboard
    cards:
      !include /config/ui-lovelace/heating.yaml

# # Камера на гараже
#     - camera_view: live
#       type: picture-glance
#       title: garage
#       camera_image: camera.garage
#       entities:
#       - entity: camera.garage

# # Камера на навесе
#     - camera_view: live
#       type: picture-glance
#       title: garden
#       camera_image: camera.garden
#       entities:
#       - entity: camera.garden

# # Камера на столбе
#     - camera_view: live
#       type: picture-glance
#       title: street
#       camera_image: camera.street
#       entities:
#       - entity: camera.street

  # - title: TV
  #   icon: mdi:television-classic
  #   cards:
      
  #       !include ui-lovelace/tv_remote.yaml
      
  - title: test
    icon: mdi:view-dashboard


  #   - type: area
  #     area: bedroom
  #     theme: green

