views:

  - title: Home
    icon: mdi:view-dashboard
    cards:
      !include ui-lovelace/home.yaml

  - title: Heating
    icon: mdi:home-thermometer
    cards:
      !include ui-lovelace/heating.yaml

  - title: Energy
    icon: mdi:flash
    cards:
      !include ui-lovelace/energy.yaml

  - title: Gas
    icon: mdi:gas-burner
    cards:
      !include ui-lovelace/gas.yaml

  - title: Rooms
    icon: mdi:exit-run
    cards:
#      !include ui-lovelace/gas.yaml

      - type: picture-glance
        title: Gostinaia
        entities:
          - entity: climate.gostinaia
          - entity: sensor.z_gostinaia_temp_temperature
        image: /local/living_room.png
        show_state: true



