views:

  - title: Home
    icon: mdi:view-dashboard
    cards:
      !include ui-lovelace/home.yaml

  - title: Heating
    icon: mdi:home-thermometer
    cards:
      !include ui-lovelace/heating.yaml

  - title: Energy
    icon: mdi:flash
    visible:
      - user: feb148ce67944832bc9d9388cf2b16af
    cards:
      !include ui-lovelace/energy.yaml

  - title: Gas
    icon: mdi:gas-burner
    cards:
      !include ui-lovelace/gas.yaml




