
# Сохранение счетчиков электрики за прошлый месяц офис
- alias: Сохранение счетчиков электрики за прошлый месяц офис
  triggers:
    - trigger: time
      at: "00:00:05"
      #это первое число месяца
  condition:
        condition: template
        value_template: "{{ now().day == 1 }}"
  actions:
    - action: input_number.set_value
      target:
        entity_id: input_number.energy_count_day_office_last_month
      data:
        value: "{{ states('sensor.energy_counter_office_day') | float }}"
    - action: input_number.set_value
      target:
        entity_id: input_number.energy_count_night_office_last_month
      data:
        value: "{{ states('sensor.energy_counter_office_night') | float }}"
