
- alias: "Автовыключение полива через 25 минут"
  mode: restart
  triggers:
    - trigger: state
      entity_id: light.zg_gw_watering_home
      to: "on"
  actions:
    - delay: "00:25:00"
    - condition: state
      entity_id: light.zg_gw_watering_home
      state: "on"
    - action: light.turn_off
      target:
        entity_id: light.zg_gw_watering_home
