- alias: "Автовыключение полива через 25 минут"
  mode: restart
  triggers:
    - trigger: state
      entity_id: light.zg_gw_watering_home
      to: "on"
  actions:
    - delay: "00:25:00"
    - condition: state
      entity_id: light.zg_gw_watering_home
      state: "on"
    - action: light.turn_off
      target:
        entity_id: light.zg_gw_watering_home

- alias: "Перекрытие воды при протечке в подвале"
  mode: single
  triggers:
    - trigger: state
      entity_id: binary_sensor.zg_gw_water_leaks_basement
      to: "on"
  actions:
    - action: light.turn_off
      target:
        entity_id:
          - light.zg_gw_central_wate_taps_osveshchenie
          - light.zg_gw_automatic_pump
    - action: light.turn_on
      target:
        entity_id: light.zg_gw_central_wate_taps_osveshchenie_2

- alias: "Восстановление воды после протечки в подвале"
  mode: restart
  triggers:
    - trigger: state
      entity_id: binary_sensor.zg_gw_water_leaks_basement
      to: "off"
  actions:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.home_power_source
              state: "grid"
          sequence:
            - action: light.turn_on
              target:
                entity_id:
                  - light.zg_gw_central_wate_taps_osveshchenie
                  - light.zg_gw_central_wate_taps_osveshchenie_2
            - delay: "00:05:00"
            - condition: state
              entity_id: light.zg_gw_central_wate_taps_osveshchenie
              state: "on"
            - condition: state
              entity_id: light.zg_gw_central_wate_taps_osveshchenie_2
              state: "on"
            - action: light.turn_on
              target:
                entity_id: light.zg_gw_automatic_pump
        - conditions:
            - condition: state
              entity_id: sensor.home_power_source
              state: "generator"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.zg_gw_central_wate_taps_osveshchenie
                  - light.zg_gw_central_wate_taps_osveshchenie_2
                  - light.zg_gw_automatic_pump
        - conditions:
            - condition: state
              entity_id: sensor.home_power_source
              state: "no_power"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.zg_gw_central_wate_taps_osveshchenie
                  - light.zg_gw_automatic_pump
            - action: light.turn_on
              target:
                entity_id: light.zg_gw_central_wate_taps_osveshchenie_2
